#!/usr/bin/env python3
"""Draw the project graphic out of the project's own data.

Every dot is one real ERC-8004 rating on Monad, coloured by where the rater's money came from, in
the same proportions the service reports: 7,896 funded by the agent's own owner, 1,206 with no
payment either way, 70 outside coverage, and 16 that survive both provenance filters. The whole
argument is that 16-to-9,188 ratio, and a ratio is the one thing a logo can actually carry.

The layout is deterministic: no randomness, so the same data always draws the same picture and the
file can be regenerated by anyone from the repo.

    python3 tools/make-logo.py            # writes web/public/logo.png, 1200x1200
"""
import json
import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
FARM = ROOT / "web" / "public" / "farm.json"
OUT = ROOT / "web" / "public" / "logo.png"

SIZE = 1200
MARGIN = 90
BG = (11, 13, 18)
# Muted for the produced ratings, bright for the ones that survived. The point of the picture is
# that the eye finds the sixteen without being told where to look.
COLOUR = {
    "ownerFunded": (86, 94, 112),
    "paidAfter": (120, 104, 84),
    "noMoney": (58, 64, 78),
    "notCovered": (44, 48, 58),
    "independent": (90, 209, 165),
}
ORDER = ["ownerFunded", "noMoney", "notCovered", "paidAfter", "independent"]


def main() -> None:
    farm = json.loads(FARM.read_text())
    totals = {b["key"]: t for b, t in zip(farm["buckets"], farm["totals"])}
    dots = [k for k in ORDER for _ in range(totals.get(k, 0))]
    n = len(dots)
    if n != farm["ratings"]:
        raise SystemExit(f"buckets sum to {n}, farm.json says {farm['ratings']}")

    # A square grid sized to the data rather than a fixed canvas: the picture is the count.
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n / cols)
    step = (SIZE - 2 * MARGIN) / cols
    radius = max(1.4, step * 0.34)

    img = Image.new("RGB", (SIZE, SIZE), BG)
    draw = ImageDraw.Draw(img)

    # The sixteen survivors are spread evenly through the field instead of stacked at the end of
    # their bucket. Grid position carries no meaning in either layout, but a contiguous run reads
    # as a category bar, while sixteen specks scattered through nine thousand read as the ratio the
    # picture is about. The spacing is computed, not random, so the image is reproducible.
    # A fixed stride would land the survivors on a diagonal, because an even step through a grid
    # aliases with the row width and draws a line that looks like a finding. Slots are chosen by a
    # multiplicative hash instead: no randomness, same picture every run, and no visible pattern.
    survivors = totals.get("independent", 0)
    rest = [k for k in dots if k != "independent"]
    slots, i = set(), 0
    while len(slots) < survivors:
        slots.add((i * 2654435761) % n)
        i += 1
    dots, feed = [], iter(rest)
    for pos in range(n):
        dots.append("independent" if pos in slots else next(feed))

    # The survivors are drawn last so they sit on top of their neighbours rather than under them.
    placed = []
    for i, key in enumerate(dots):
        col, row = i % cols, i // cols
        x = MARGIN + step * col + step / 2
        y = MARGIN + (SIZE - 2 * MARGIN - step * rows) / 2 + step * row + step / 2
        placed.append((key, x, y))
    placed.sort(key=lambda p: p[0] == "independent")

    for key, x, y in placed:
        r = radius * (2.1 if key == "independent" else 1.0)
        draw.ellipse([x - r, y - r, x + r, y + r], fill=COLOUR[key])

    img.save(OUT, "PNG", optimize=True)
    kb = OUT.stat().st_size / 1024
    print(f"{OUT} — {SIZE}x{SIZE}, {n} dots, {totals['independent']} of them independent, {kb:.0f} KB")


if __name__ == "__main__":
    main()
